### ISSUE TITLE
Discuss alternative(s) in README

### ISSUE THREAD

**Issue by andreasabel** [tbidne/package-version#3]
Maybe the README could discuss alternatives.

E.g. I use the version provided by the `cabal`-generated `Paths_XXX` package:
```haskell
module Version ( version ) where

import Data.List ( intercalate )
import Data.Version ( Version(versionBranch) )

import qualified Paths_PACKAGE as Paths

-- | The program version obtained from the cabal file.

version :: String
version = intercalate "." $ map show $ versionBranch Paths.version
```
Of course, this requires that `cabal build` has run, but maybe this runs anyway at compile time.

**Comment by tbidne** [comment]
Indeed, I believe you are correct that `Paths_PKG` subsumes the `read version at compile time` functionality here. Embarrassingly, I was unaware of this.

Thanks for bringing this to my attention! I am happy to highlight this alternative. I opened a PR at #4; the rendered change is below:

---

## Alternatives

Reading the cabal version can also be achieved by utilizing the generated `Paths_<pkg-name>` module. For instance, for a package named `foo`, we first add the generated module to our list of modules in `foo.cabal`:

```cabal
cabal-version:      2.4
name:               foo
version:            0.1

...

library
  other-modules: Paths_foo
```

Then we can reference this in our code:

```haskell
import Data.List (intercalate)
import Data.Version (Version(versionBranch))
import Paths_foo qualified as Paths
vsn :: String
vsn = intercalate "." $ fmap show $ versionBranch Paths.version
```

See the [source](https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs) regarding the API.

---

Does this look good to you? (I couldn't find a better reference for the `Paths_X` module than the source).

**Comment by andreasabel** [comment]
> Does this look good to you?

Great!
See also my review comments.

**Comment by tbidne** [comment]
Thanks again!
