### ISSUE TITLE
cabal file on hackage lags in deps

### ISSUE THREAD

**Issue by ysangkok** [tbidne/package-version#5]
you have updated the bounds of tasty-hedgehog here on github, but on hackage the bound `<1.4` is still present. haven't checked doctest but it might have the same issue.

**Comment by tbidne** [comment]
Hi, thanks for the heads up. Can you clarify the problem you are encountering? I am looking at the latest revision for each release, and they seem up to date to me:

- [`0.1.0.0`](https://hackage.haskell.org/package/package-version-0.1.0.0/revision/6.cabal)
- [`0.2`](https://hackage.haskell.org/package/package-version-0.2/revision/5.cabal)
- [`0.3`](https://hackage.haskell.org/package/package-version-0.3/revision/3.cabal)

In particular, the `tasty-hedgehog` bounds are all `<1.5`.

**Comment by ysangkok** [comment]
Ah sorry, I must have been looking at the original Cabal file instead of the revision. Apologies!

**Comment by tbidne** [comment]
No problem, thanks for checking!
